name: Deploy to cPanel

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}

    - name: Deploy to cPanel via SSH
      run: |
        ssh -o StrictHostKeyChecking=no username@your-cpanel-domain.com "
          cd /home/username/public_html/your-app-directory &&
          git pull origin main &&
          composer install --no-dev &&
          php artisan migrate --force
        "
