name: Deploy to cPanel

on:
  push:
    branches:
      - main   # Change this if you're deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.CPANEL_SSH_KEY }}

    - name: Deploy to cPanel via SSH and Git Pull
      run: |
        ssh -o StrictHostKeyChecking=no boxgra6@joseph.califorsale.org "
          cd ~/test.califorsale.org &&
          git pull origin main
        "
